name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.7
      
      - name: Restore NuGet Packages
        run: nuget restore Application/UnityDonors/UnityDonors.sln
      
      - name: Build Solution
        run: msbuild Application/UnityDonors/UnityDonors.sln /p:Configuration=Release
